stages:
 - build
 - upload

# multiarch images for jessie are no longer updated and were left in a bad state
.fix_jessie_multiarch_apt_sources: &fix_jessie_multiarch_apt
  /bin/sed -i 's/^\(.*jessie-updates main\)$/# \1/' /etc/apt/sources.list

# multiarch images only include the main component, and equivs is in universe
.fix_ubuntu_multiarch_apt_template: &fix_ubuntu_multiarch_apt
  /bin/sed -i 's/main$/main restricted universe/' /etc/apt/sources.list

.generic_apt_build_template: &generic_apt_build
  apt-get update && apt-get -y upgrade &&
  apt-get install -y ca-certificates devscripts dpkg-dev equivs lsb-release &&
  export DEBEMAIL='brendonj@waikato.ac.nz' &&
  export DEBFULLNAME='Brendon Jones' &&
  export CODENAME=`lsb_release -c -s` &&
  mk-build-deps -i -r -t 'apt-get -f -y --force-yes' &&
  dpkg-buildpackage -b -us -uc -rfakeroot &&
  mkdir -p built-packages/$CODENAME/ || true &&
  mv ../*.deb built-packages/$CODENAME/

.build_template: &build_template
  stage: build
  script:
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-bionic-amd64:
  <<: *build_template
  image: ubuntu:bionic

build-bionic-i386:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:i386-bionic
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_build

build-bionic-armhf:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:armhf-bionic
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_build

#build-bionic-arm64:
#  <<: *build_template
#  image: multiarch/ubuntu-debootstrap:arm64-bionic
#  script:
#    - *fix_ubuntu_multiarch_apt
#    - *generic_apt_build


build-xenial-amd64:
  <<: *build_template
  image: ubuntu:xenial

build-xenial-i386:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:i386-xenial
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_build

build-xenial-armhf:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:armhf-xenial
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_build

#build-xenial-arm64:
#  <<: *build_template
#  image: multiarch/ubuntu-debootstrap:arm64-xenial
#  script:
#    - *fix_ubuntu_multiarch_apt
#    - *generic_apt_build

build-stretch-amd64:
  <<: *build_template
  image: debian:stretch

build-stretch-i386:
  <<: *build_template
  image: multiarch/debian-debootstrap:i386-stretch

build-stretch-armhf:
  <<: *build_template
  image: multiarch/debian-debootstrap:armhf-stretch

#build-stretch-arm64:
#  <<: *build_template
#  image: multiarch/debian-debootstrap:arm64-stretch

build-jessie-amd64:
  <<: *build_template
  image: debian:jessie

build-jessie-i386:
  <<: *build_template
  image: multiarch/debian-debootstrap:i386-jessie
  before_script:
      - *fix_jessie_multiarch_apt

build-jessie-armhf:
  <<: *build_template
  image: multiarch/debian-debootstrap:armhf-jessie
  before_script:
      - *fix_jessie_multiarch_apt

#build-jessie-arm64:
#  <<: *build_template
#  image: multiarch/debian-debootstrap:arm64-jessie
#  before_script:
#    - *fix_jessie_multiarch_apt

upload-packages:
  stage: upload
  image: ubuntu:bionic
  script:
    - ./bintray-upload.sh
  only:
    - tags
